# Python Numpy : Data Types for ndarrays

In [4]:
import numpy as np

## assign and check data type

In [42]:
# 1. making array with data type of float64
aaa = np.array([1.4, 2.6, 3.0, 4.9], dtype=np.float64)

In [43]:
aaa.dtype

dtype('float64')

In [44]:
aaa

array([ 1.4,  2.6,  3. ,  4.9])

In [45]:
# 2. making array with shorthand type string
bbb = np.array([1.4, 2.6, 3.0, 4.9], dtype='f8')

In [25]:
bbb.dtype

dtype('float64')

In [26]:
bbb

array([ 1.4,  2.6,  3. ,  4.9])

In [27]:
# 3. making array with data type of float6.4

In [28]:
ccc = np.float64([1.4, 2.6, 3.0, 4.9])

In [29]:
ccc.dtype

dtype('float64')

In [30]:
ccc

array([ 1.4,  2.6,  3. ,  4.9])

## converting data type

In [31]:
aaa

array([ 1.4,  2.6,  3. ,  4.9])

In [32]:
aaa.dtype

dtype('float64')

In [33]:
# converting float64 into int64
ddd = aaa.astype(np.int64)

In [34]:
ddd.dtype

dtype('int64')

In [35]:
ddd

array([1, 2, 3, 4], dtype=int64)

In [36]:
# convert float64 into int64 using np.int64(obj)
eee = np.int64(aaa)

In [37]:
eee.dtype

dtype('int64')

In [38]:
eee

array([1, 2, 3, 4], dtype=int64)

In [39]:
aaa

array([ 1.4,  2.6,  3. ,  4.9])

In [47]:
# converting float64 into string
x_string = aaa.astype(np.string_)

In [48]:
x_string.dtype

dtype('S32')

In [49]:
x_string

array([b'1.4', b'2.6', b'3.0', b'4.9'], 
      dtype='|S32')

In [53]:
# from string to float64
tanos = x_string.astype(np.float64)

In [54]:
tanos

array([ 1.4,  2.6,  3. ,  4.9])

In [55]:
tanos.dtype

dtype('float64')