# Python Numpy data types 지정, 확인, 변경

In [1]:
import numpy as np

## assigning data type

In [4]:
# making array with data type of float64
x_float64 = np.array([1.4, 2.6, 3.0, 5.0, 5.32], dtype=np.float64)

In [5]:
x_float64

array([ 1.4 ,  2.6 ,  3.  ,  5.  ,  5.32])

In [6]:
# checking data type
x_float64.dtype

dtype('float64')

In [19]:
# making array with shorthand type code
x_float64_1 = np.array([1.4, 2.6, 3.0, 4.9, 5.32], dtype='f8')

In [20]:
x_float64_1.dtype

dtype('float64')

In [25]:
# making array with data type
x_float64_2 = np.float64([1.4, 2.6, 3.0, 4.9, 5.32])

In [26]:
x_float64_2.dtype

dtype('float64')

## converting data type

In [27]:
x_float64

array([ 1.4 ,  2.6 ,  3.  ,  5.  ,  5.32])

In [28]:
# way 1: converting float64 into int64 
x_int64 = x_float64.astype(np.int64)

In [29]:
x_int64.dtype

dtype('int64')

In [30]:
x_int64

array([1, 2, 3, 5, 5], dtype=int64)

In [31]:
# way 2
x_int64_2 = np.int64(x_float64)

In [32]:
x_int64_2.dtype

dtype('int64')

In [34]:
# converting float64 into string
x_string = x_float64.astype(np.string_)

In [35]:
x_string.dtype

dtype('S32')

In [36]:
x_string

array([b'1.4', b'2.6', b'3.0', b'5.0', b'5.32'], 
      dtype='|S32')

In [37]:
# converting string into float64
x_from_string_to_float64 = x_string.astype(np.float64)

In [38]:
x_from_string_to_float64

array([ 1.4 ,  2.6 ,  3.  ,  5.  ,  5.32])