# Ramdon Numbers Generation

In [1]:
import numpy as np

## 1. generating random numbers from normal distribution

In [27]:
np.random.normal(size=1)

array([ 1.14745744])

In [4]:
np.random.normal(size=5)

array([ 0.1101033 ,  0.53520633,  2.08690999, -0.44211682,  2.12765678])

In [5]:
np.random.normal(size=5)

array([-0.13389851, -0.99964215,  0.53406577, -0.65366134, -0.06533874])

In [6]:
# setting the seed number(초기값) for reproducibility(재현가능성)
np.random.seed(seed=100)

In [7]:
np.random.normal(size=5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [15]:
np.random.seed(seed=100)
np.random.normal(size=5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [13]:
np.random.seed(seed=123)
np.random.normal(size=5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [12]:
np.random.seed(seed=123)
np.random.normal(size=5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [17]:
# size: 샘플 생성(추출) 개수 및 array shape 설정
np.random.normal(size=2)

array([-1.07004333, -0.18949583])

In [21]:
np.random.normal(size=(2, 3))

array([[ 1.36155613, -0.32623806,  0.05567601],
       [ 0.22239961, -1.443217  , -0.75635231]])

In [22]:
np.random.normal(size=(2, 3, 4))

array([[[ 0.81645401,  0.75044476, -0.45594693,  1.18962227],
        [-1.69061683, -1.35639905, -1.23243451, -0.54443916],
        [-0.66817174,  0.00731456, -0.61293874,  1.29974807]],

       [[-1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ],
        [ 1.47071387, -1.1880176 , -0.54974619, -0.94004616],
        [-0.82793236,  0.10886347,  0.50780959, -0.86222735]]])

In [24]:
np.random.normal(size=(3, 4, 5))

array([[[ 0.42238022, -1.09404293,  1.23690789, -0.23028468, -0.7044182 ],
        [-0.59137512,  0.73699517,  0.43586725,  1.77599359,  0.51307438],
        [ 1.17052698,  2.07771223, -0.45592202,  0.64917293, -0.17478155],
        [ 1.01726434, -0.59998304,  1.57616672,  0.60442354, -0.90703042]],

       [[ 0.59202327, -0.43706442,  0.10177577,  1.30834683,  1.38760181],
        [-1.73539115,  0.28837742, -0.33908543,  0.52736913, -0.37430288],
        [ 0.4770923 , -1.42976266,  0.40770652, -0.82828039,  0.42345728],
        [-0.15951737,  1.24108209,  1.66353631, -0.66193771,  3.46522715]],

       [[ 0.39143862,  0.32724535, -0.31134706, -1.42465559, -0.62487219],
        [-0.1099954 ,  0.95295943, -0.98336264, -1.09455719, -0.24134875],
        [-0.59511384, -0.98281189,  0.08822993, -0.60275937,  1.12555545],
        [ 0.9270533 , -2.26915699, -0.34817064, -0.1640254 ,  1.21658059]]])

In [32]:
np.random.normal(size=(2, 2, 2, 2))

array([[[[-0.09180805, -0.81056012],
         [ 1.99985784, -0.79047271]],

        [[ 1.27203493,  0.12340671],
         [-0.14471977,  0.06339993]]],


       [[[ 0.03104795, -1.73909927],
         [ 0.08649406, -0.49104597]],

        [[-2.67435495,  0.64435936],
         [-0.14505356,  0.81169105]]]])

## 2. generating random numbers from binomial distribution

In [34]:
np.random.binomial(n=1, p=0.5, size=20)

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [37]:
np.random.binomial(n=1, p=0.9, size=20)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
np.random.binomial(n=1, p=0.2, size=20)

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [46]:
np.random.binomial(n=1, p=0.5, size=20)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1])