# Broadcasting w/ Numpy 1D array

In [1]:
import numpy as np

In [4]:
a_ar = np.array([1., 2., 3., 4.])

In [5]:
a_ar.shape

(4,)

In [6]:
a_ar+1

array([2., 3., 4., 5.])

# Braodcasting w/ DataFrame 

In [7]:
import pandas as pd

In [8]:
a_df = pd.DataFrame({'x1': [1, 2, 3, 4], 'x2' : [5, 6, 7, 8]})

In [9]:
a_df

x1  x2
0   1   5
1   2   6
2   3   7
3   4   8

In [10]:
a_df+1

x1  x2
0   2   6
1   3   7
2   4   8
3   5   9

# broadcasting over axis 0 with 1D array

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
b = np.arange(12).reshape((4, 3))

In [15]:
b.shape

(4, 3)

In [13]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
c = np.array([0, 1, 2])

In [19]:
c.shape

(3,)

In [20]:
c

array([0, 1, 2])

In [21]:
b+c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [24]:
b = np.arange(12).reshape((4, 3))

In [25]:
b.shape

(4, 3)

In [26]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
e = np.array([0, 1, 2, 3]).reshape(4, 1)

In [28]:
e.shape

(4, 1)

In [29]:
e

array([[0],
       [1],
       [2],
       [3]])

In [30]:
b+e

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

# Broadcasting over axis 0 with a 3-D array

In [37]:
f = np.arange(24).reshape((2, 4, 3))

In [38]:
f

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [39]:
g = np.ones((4, 3))

In [40]:
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
f + g

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]]])