# Python NumPy 다차원 배열 ndarray 만들기

In [15]:
# import numpy module
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
# list를 배열로 변환
data_list = [6, 7, 8, 9, 10]
arr2 = np.array(data_list)

In [7]:
arr2

array([ 6,  7,  8,  9, 10])

In [27]:
# converting a list of equal-length lists into a multi-dimensional array
data_lists = [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 10, 20]]

In [28]:
arr12 = np.array(data_lists)

In [29]:
arr12

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 20]])

In [30]:
# shape method
arr12.shape

(2, 6)

In [31]:
arr12.shape[0]

2

In [32]:
arr12.shape[1]

6

In [33]:
arr12.dtype

dtype('int32')

In [34]:
# np.asarray()
a = [1, 2, 3, 4, 5]

In [35]:
type(a)

list

In [36]:
a = np.asarray(a)

In [37]:
type(a)

numpy.ndarray

In [38]:
a

array([1, 2, 3, 4, 5])

In [50]:
# Copy

In [42]:
b = np.array([0, 0, 1, 1, 2])
b

array([0, 0, 1, 1, 2])

In [40]:
c = b.copy()

In [41]:
c

array([0, 0, 1, 1, 2])

In [43]:
c[0] = 50

In [44]:
c

array([50,  0,  1,  1,  2])

In [45]:
b

array([0, 0, 1, 1, 2])

In [46]:
d = b

In [47]:
d[0] = 100

In [48]:
d

array([100,   0,   1,   1,   2])

In [49]:
b

array([100,   0,   1,   1,   2])

In [58]:
# floating point ndarray
d = [6, 7, 8, 9, 10]
d

[6, 7, 8, 9, 10]

In [60]:
np.asfarray(d)

array([  6.,   7.,   8.,   9.,  10.])

In [61]:
# np.asarray_chkfinite()
e = [11, 12, 13, 14, 15]

In [62]:
np.asarray_chkfinite(e, dtype=float)

array([ 11.,  12.,  13.,  14.,  15.])

In [65]:
e_2 = [11, 12, 13, np.nan, 15]

In [67]:
np.asarray_chkfinite(e_2, dtype = float)

ValueError: array must not contain infs or NaNs

In [71]:
e_3 = [11, 12, 13, 14, np.inf]

In [72]:
np.asarray_chkfinite(e_3, dtype=float)

ValueError: array must not contain infs or NaNs