In [1]:
import numpy as np

In [112]:
x = np.array([1., 1., 2., 2.])

In [3]:
y = np.array([1., 2., 3., 4.])

In [4]:
x

array([1., 1., 2., 2.])

In [5]:
y

array([1, 2, 3, 4])

# (1) 배열과 스칼라의 산술 연산 (Arithmetic operations with an array and scalar)

In [7]:
x + 1

array([2., 2., 3., 3.])

In [12]:
x-1

array([0., 0., 1., 1.])

In [13]:
x*0

array([0., 0., 0., 0.])

In [14]:
x/2

array([0.5, 0.5, 1. , 1. ])

In [15]:
x//2

array([0., 0., 1., 1.])

In [16]:
x%2

array([1., 1., 0., 0.])

In [17]:
y**2

array([ 1,  4,  9, 16], dtype=int32)

In [18]:
2**y

array([ 2,  4,  8, 16], dtype=int32)

# (2) 같은 크기 배열 간 산술 연산

In [19]:
x+y

array([2., 3., 5., 6.])

In [20]:
x-y

array([ 0., -1., -1., -2.])

In [21]:
x*y

array([1., 2., 6., 8.])

In [23]:
y/x

array([1. , 2. , 1.5, 2. ])

In [25]:
y//x

array([1., 2., 1., 2.])

In [26]:
y%x

array([0., 0., 1., 0.])

In [27]:
y**x

array([ 1.,  2.,  9., 16.])

# (3) 배열 간 비교 연산

In [32]:
x

array([1., 1., 2., 2.])

In [33]:
y

array([1, 2, 3, 4])

In [28]:
np.equal(x, y)

array([ True, False, False, False])

In [29]:
np.not_equal(x, y)

array([False,  True,  True,  True])

In [30]:
np.greater(x, y)

array([False, False, False, False])

In [31]:
np.greater(y, x)

array([False,  True,  True,  True])

In [36]:
np.greater_equal(x, y)

array([ True, False, False, False])

In [37]:
np.greater_equal(y, x)

array([ True,  True,  True,  True])

In [38]:
np.less_equal(x, y)

array([ True,  True,  True,  True])

In [40]:
np.less(x, y)

array([False,  True,  True,  True])

In [41]:
np.array_equal(x, y)

False

In [42]:
z = y.copy()

In [43]:
z

array([1, 2, 3, 4])

In [44]:
np.array_equal(y, z)

True

# (4) 배열 간 할당 연산

In [79]:
m = np.array([1., 1., 2., 2.])

In [80]:
n = np.array([1., 2., 3., 4.])

In [52]:
m += n

In [53]:
m

array([ 3,  5,  8, 10])

In [54]:
m = np.array([1, 1, 2, 2])

In [55]:
m -= n

In [56]:
m

array([ 0, -1, -1, -2])

In [75]:
m = np.array([1., 1., 2., 2.])

In [58]:
m *= n # m = m * n

In [59]:
m

array([1, 2, 6, 8])

In [81]:
m = np.array([1., 1., 2., 2.])

In [65]:
m = m/n

In [66]:
m

array([1.        , 0.5       , 0.66666667, 0.5       ])

In [64]:
n

array([1, 2, 3, 4])

In [82]:
m /= n

In [83]:
m

array([1.        , 0.5       , 0.66666667, 0.5       ])

In [84]:
m = np.array([1., 1., 2., 2.])

In [85]:
m //= n

In [86]:
m

array([1., 0., 0., 0.])

In [87]:
m = np.array([1., 1., 2., 2.])

In [89]:
m %= n

In [90]:
m

array([0., 1., 2., 2.])

In [91]:
m = np.array([1., 1., 2., 2.])

In [92]:
m **= n

In [93]:
m

array([ 1.,  1.,  8., 16.])

In [98]:
m = np.array([1., 1., 2., 2.])

In [99]:
m **= m

In [100]:
m

array([1., 1., 4., 4.])

# (5) 배열 간 논리 연산

In [101]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [102]:
np.logical_and(a, b)

array([ True, False, False, False])

In [103]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [104]:
np.logical_xor(a, b)

array([False,  True,  True, False])

# (6) 소속 여부 판단 연산

In [105]:
p = "p"

In [106]:
q = np.array(["p", "q"])

In [107]:
r = np.array(["r", "s"])

In [108]:
p in q

True

In [109]:
p in r

False

In [110]:
p not in q

False

In [111]:
p not in r

True